services:
  redis:
    image: redis:alpine
    container_name: fila-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    container_name: queue-app
    ports:
      - "80:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

volumes:
  redis-data:
